services:
  db:
    image: postgres
    volumes:
    - postgresql_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  web:
    image: ${CI_REGISTRY_IMAGE:-local/django_poll}:${CI_COMMIT_REF_SLUG:-local}
    build: .
    command: bash -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn django_poll.wsgi --workers 2 --bind 0.0.0.0:8000
      "
    ports:
    - "8000:8000"
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    depends_on:
    - db

volumes:
  postgresql_data: